import type { Product } from "@/types/product";

export const fallbackProducts: Product[] = [
  {
    id: 1,
    name: "AeroPods Max",
    description: "Adaptive noise canceling earbuds with spatial sound.",
    price: 129.99,
    oldPrice: 169.99,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1590658165737-15a047b0d41d?w=900",
    category: "Audio",
    store: "pulse-gear",
    inStock: true,
    rating: 4.8,
    stockCount: 48,
  },
  {
    id: 2,
    name: "Stride Watch S4",
    description: "GPS fitness watch with recovery score and sleep coach.",
    price: 199,
    oldPrice: 239,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900",
    category: "Wearables",
    store: "urban-active",
    inStock: true,
    rating: 4.6,
    stockCount: 30,
  },
  {
    id: 3,
    name: "Vision 4K 27",
    description: "4K USB-C monitor with HDR and factory color calibration.",
    price: 329.99,
    oldPrice: 379.99,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1527443224154-c4cebe9f0e0e?w=900",
    category: "Displays",
    store: "studio-screen",
    inStock: true,
    rating: 4.7,
    stockCount: 16,
  },
  {
    id: 4,
    name: "NovaPhone 15",
    description: "Flagship phone with cinematic camera and AI assist.",
    price: 799,
    oldPrice: 899,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=900",
    category: "Phones",
    store: "mobile-lane",
    inStock: true,
    rating: 4.9,
    stockCount: 22,
  },
];

export const fallbackCategories = [
  "Audio",
  "Wearables",
  "Accessories",
  "Displays",
  "Phones",
  "Computers",
];

